### ISSUE TITLE
error during download

### ISSUE THREAD

**Issue by Dagmear456** [gamestabled/OoT3D_Randomizer#749]
getting an error when trying to download new version

**Comment by gymnast86** [comment]
This should be fixed now if you try downloading the new version

**Comment by Dagmear456** [comment]
still getting the error
![20240802_074128](https://github.com/user-attachments/assets/b6fd4713-1a61-4eed-9045-7c5e80800675)

**Comment by PhlexPlexico** [comment]
Did you try with this nightly? https://github.com/gamestabled/OoT3D_Randomizer/releases/tag/Nightly-c3ece3

**Comment by Dagmear456** [comment]
it worked thank you

**Comment by PhlexPlexico** [comment]
No problem!
